### ISSUE TITLE
Error when doing forward/backward rnn module after calling weights() or bias()

### ISSUE THREAD

**Issue by SeanNaren** [soumith/cudnn.torch#246] opened 2016-08-18 10:49 UTC
Hey I'm running into an error when saving/loading the module after calling weights() or bias(). Can be reproduced below:

```lua
require 'cudnn'

local input = torch.randn(1, 1, 5):cuda()

local rnn = cudnn.RNNReLU(5, 5, 1):cuda()
print(rnn:forward(input))

local weights = rnn:weights()
local biases = rnn:biases()

torch.save('temp.t7', rnn)
local rnn = torch.load('temp.t7')

print(rnn:forward(input))
```

Thanks!

**Comment by albanD** [comment] 2016-08-18 11:07
The call to `cudnnGetFilterNdDescriptor` [here](https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L589-L595) modifies the strings `dataType`, `format` and `self.datatype` and remove the first part of them: for example `CUDNN_DATA_FLOAT` becomes `N_DATA_FLOAT`. This leads to an error when you try to save the model because the datatype is wrong.
I am not sure why this function call does that though...

**Comment by albanD** [comment] 2016-08-18 11:45
Ok the problem is that cudnn actually modifies the string that we give it (for some reason) and in this case, it modifies the lua internalized strings.

**Comment by SeanNaren** [comment] 2016-08-18 12:52
Strange issue hopefully someone can explain why this occurs... @albanD any workaround possible at the time being? Thanks!

**Comment by albanD** [comment] 2016-08-18 14:25
You can use [this](https://github.com/albanD/cudnn.torch/tree/string_fix) branch as a temporary fix. I am not 100% sure this is the best way to solve this, but will do until we find a long term solution.

**Comment by soumith** [comment] 2016-08-18 14:29
thanks to Alban, this is fixed in trunk.

**Closed by soumith** 2016-08-18 14:29 UTC

**Comment by SeanNaren** [comment] 2016-08-18 14:31
Thanks @albanD!
